specVersion: "0.2.0"

name: "Moonriver EVM Starter Project"
version: "1.0.0"
description: "A basic Moonriver EVM example project with an event and call handler. Read more about this at https://doc.subquery.network/create/moonbeam/"
repository: "https://github.com/subquery/tutorials-moonriver-evm-starter"

schema:
  file: "./schema.graphql"

network:
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b' # Genesis hash of Moonriver
  endpoint: wss://moonriver.api.onfinality.io/public-ws
  # Optionally provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: 'https://api.subquery.network/sq/subquery/moonriver-dictionary'

  chaintypes:
    file: "./types.yaml"

dataSources:
  - kind: substrate/Moonbeam
    startBlock: 915670
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        abi: erc20
    assets:
      erc20:
        file: './abis/erc20.abi.json'
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleTransferEvent
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Transfer(address indexed from,address indexed to,uint256 value)
              - null
              - null
              - null
       